### PR TITLE
Answers -> Search

### PR DESCRIPTION
**Pull request by ElemelonWind**
## Version 0.2.0-beta.243
`@yext/answers-react-components` is now `@yext/search-ui-react`!

### Changes
- Exported a string representing the content path to files in component lib that uses tailwind classnames. (#193)
- Trimmed/edited various CSS classes  interfaces. (#189, #190, #191, #194, #196, #197, #198, #200, #202)
- Made hovering over `FilterSearch` autocomplete suggestions trigger a highlight on the selected option and fixed its width/padding. (#203, #205)
- Removed `allowPagination` prop from `VerticalResults` (#217, #219)
- Updated `StandardFacets` to optionally display the number of results associated with each facet option. (#226, #248)
- Added a 'clear filter' feature for 'clear min and max' button in `RangeInput`. (#227)
- Added a range to the `ResultCount` that describes the range of results currently displayed by `Pagination`. (#228)
- Replaced `onSubmit` with `dropdownItemProps` in `RenderEntityPreviews` interface. (#225, #238)
- Separated recent searches in verticals to keep their recent search histories separate. (#242)
- Removed links from `AlternativeVerticals` and deleted `UniversalLink` interface. (#229)
- `@yext/answers-headless-react` has been renamed to `@yext/search-headless-react`, and has been replaced by such as a peer dependency. (#243)

### Bugfixes
- When `label` is undefined, `FilterSearch` does not display default 'filter' label (#201)
- Fixed `DropdownMenu` tabbing and selecting behavior (#206, #207)
- Fixed a bug where clicking the `ApplyFiltersButton` did not reset the pagination offset. (#213)
- Fixed linebreak bug in `resultsCount` (#218)
- Fixed a bug where range input static filters were removed when selecting/de-selecting facet options with different `fieldId`s. (#224)
- Fixed `LocationBias` mobile styling (#221)
- Fixed `ThumbsFeedback` issues of not having a default width and height, as well as rotation issue with the thumbs-down button. (#233)
- Fixed `inputPrefix` collision issue and tooltip location in `RangeInput`. (#232, #234)
- Fixed a bug where facets were not being reset when applying a filter from `FilterSearch` with `searchOnSelect=true`. (#236)

### CODE REVIEW

**Comment by ElemelonWind** [comment]
Coveralls is acting up :( Will rerun in an hour or so!

**Review by nmanu1 — COMMENTED** [review]
can you update the PR description with the changes?

**Comment by ElemelonWind** [comment]
> can you update the PR description with the changes?

I don't think anything other than the name (and the internal imports/variables) was changed, how should I say that?

**Review by nmanu1 — COMMENTED** [review]
If we're making a new beta version, the `package.json` version should be updated. And we probably want to add the other changes since the last beta version in the PR description/release notes

**Comment by nmanu1** [comment]
> Where can I find all the other changes?

If you look in the commit history for `main`, you can see all the commits since the last beta PR (#184) was merged in

**Comment by ElemelonWind** [comment]
> > Where can I find all the other changes?
> 
> If you look in the commit history for `main`, you can see all the commits since the last beta PR (#184) was merged in

Updated, but I think it looks a bit messy- are there any that I don't need to mention?

**Comment by nmanu1** [comment]
> Updated, but I think it looks a bit messy- are there any that I don't need to mention?

For the CSS class interface updates, I don't think you need to list them all individually. Maybe just mention that we trimmed some of those interfaces and then list all the relevant PRs. You might also be able to group some of the fixes by component to make it more streamlined

**Comment by ElemelonWind** [comment]
> > Updated, but I think it looks a bit messy- are there any that I don't need to mention?
> 
> For the CSS class interface updates, I don't think you need to list them all individually. Maybe just mention that we trimmed some of those interfaces and then list all the relevant PRs. You might also be able to group some of the fixes by component to make it more streamlined

edited!

**Comment by nmanu1** [comment]
the latest commit on main (#248) should also be added in the description. it can be grouped with the third point under Changes about the `StandardFacets` count

**Comment by ElemelonWind** [comment]
> the latest commit on main (#248) should also be added in the description. it can be grouped with the third point under Changes about the `StandardFacets` count

Done :)

**Comment by ElemelonWind** [comment]
Coveralls still isn't working :(

**Comment by nmanu1** [comment]
I think these PRs would also be good to include in the description: #193, #201, #203, #205

**Comment by ElemelonWind** [comment]
> I think these PRs would also be good to include in the description: #193, #201, #203, #205

added!

**Comment by nmanu1** [comment]
A couple more PRs to add: #194 and #198 (these can go with the other css trimming PRs), and #197 (also kind of related)

**Comment by nmanu1** [comment]
> Coveralls still isn't working :(

looks like they're having an outage: https://status.coveralls.io/

**Comment by alextaing** [comment]
I think they're back up!

**Review by yen-tt — APPROVED** [review]

**Pull request merged**
